name: Translations diff check

on: [pull_request]

jobs:
  translation-check:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Here"
      - uses: utsav00/actions/dist/translations_diff@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: ${{ github.head_ref }}
      - run: echo "Over"