name: Crowdin Notification Listener

on:
  repository_dispatch:
    types: [create_crowdin_task]

jobs:
  crowdin_webhook_trigger:
    runs-on: ubuntu-latest

    steps:
        - uses: SpringCare/actions/dist/create_crowdin_task@feature/GT-47-crowdin-webhook-trigger
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            crowdin-token: ${{ secrets.CROWDIN_TOKEN }}
            github_context: ${{ toJson(github.event.client_payload) }}

        - run: echo "Triggered"
